/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Socket.Client;

/**
 *
 * @author Steven
 */
public class ClientInterface extends javax.swing.JFrame {

    private RetrieveInterface ri;
    private UpdateInterface ui;
    private CreateInterface ci;
    private DeleteInterface di;

    /**
     * Creates new form Client
     */
    public ClientInterface() {
        initComponents();
        this.setVisible(true);
        this.ri = new RetrieveInterface();
        this.ui = new UpdateInterface();
        this.ci = new CreateInterface();
        this.di = new DeleteInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        btnCreate = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFinalize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Socket protocol and XML");

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRetrieve.setText("Retrieve");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFinalize.setText("Finalize");
        btnFinalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnCreate)
                .addGap(70, 70, 70)
                .addComponent(btnRetrieve)
                .addGap(68, 68, 68)
                .addComponent(btnUpdate)
                .addGap(54, 54, 54)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnFinalize)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRetrieve)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnFinalize))
                .addGap(34, 34, 34)
                .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//accion del boton retrieve
    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        //valido si alguna ventana esta abierta para cerrarla o si la ventana que voy a abrir ya esta abierta
        if (!this.ri.isShowing()) {
            if(this.ci.isShowing()){
                this.ci.dispose();
            }
            if(this.ui.isShowing()){
                this.ui.dispose();
            }
            if(this.di.isShowing()){
                this.di.dispose();
            }
            this.ri = new RetrieveInterface();
            this.dp.add(this.ri);
        }
    }//GEN-LAST:event_btnRetrieveActionPerformed
//accion del boton create
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        //valido si alguna ventana esta abierta para cerrarla o si la ventana que voy a abrir ya esta abierta
        if (!this.ci.isShowing()) {
            if(this.ri.isShowing()){
                this.ri.dispose();
            }
            if(this.ui.isShowing()){
                this.ui.dispose();
            }
            if(this.di.isShowing()){
                this.di.dispose();
            }
            this.ci = new CreateInterface();
            this.dp.add(this.ci);
        }
    }//GEN-LAST:event_btnCreateActionPerformed
//accion del boton update
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //valido si alguna ventana esta abierta para cerrarla o si la ventana que voy a abrir ya esta abierta
        if (!this.ui.isShowing()) {
            if(this.ci.isShowing()){
                this.ci.dispose();
            }
            if(this.ri.isShowing()){
                this.ri.dispose();
            }
            if(this.di.isShowing()){
                this.di.dispose();
            }
            this.ui = new UpdateInterface();
            this.dp.add(this.ui);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
//accion del boton delete
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //valido si alguna ventana esta abierta para cerrarla o si la ventana que voy a abrir ya esta abierta
        if(!this.di.isShowing()){
            if(this.ci.isShowing()){
                this.ci.dispose();
            }
            if(this.ui.isShowing()){
                this.ui.dispose();
            }
            if(this.ri.isShowing()){
                this.ri.dispose();
            }
            this.di = new DeleteInterface();
            this.dp.add(this.di);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
//accion del boton finalize
    private void btnFinalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizeActionPerformed
        this.ci.finalize();
        System.exit(0);
    }//GEN-LAST:event_btnFinalizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFinalize;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JDesktopPane dp;
    // End of variables declaration//GEN-END:variables
}
