/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.Student;
import Socket.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class RetrieveInterface extends javax.swing.JInternalFrame {

    private Client client;

    /**
     * Creates new form RetrieveInterface
     */
    public RetrieveInterface() {
        initComponents();
        this.buttonGroup1.add(this.rdName);
        this.buttonGroup1.add(this.rdId);
        this.rdName.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        rdName = new javax.swing.JRadioButton();
        rdId = new javax.swing.JRadioButton();
        txtEntry = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Retrieve a student");
        setVisible(true);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        taResult.setEditable(false);
        taResult.setColumns(20);
        taResult.setRows(5);
        jScrollPane1.setViewportView(taResult);

        jLabel1.setText("Search for a student by:");

        rdName.setText("Name");

        rdId.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdId)
                    .addComponent(rdName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEntry)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rdName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//accion del boton create
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        this.client = new Client();
        this.client.setPetitionType('R');
        Student searched = new Student();
        if (this.rdId.isSelected() && !this.txtEntry.getText().isEmpty()) {
            try {
                searched = this.client.idRetrieve(this.txtEntry.getText());
            } catch (IOException ex) {
                Logger.getLogger(RetrieveInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (this.rdName.isSelected() && !this.txtEntry.getText().isEmpty()) {
            try {
                searched = this.client.nameRetrieve(this.txtEntry.getText());
            } catch (IOException ex) {
                Logger.getLogger(RetrieveInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (searched.getAge() == 0) {
            JOptionPane.showMessageDialog(this, "The id or the name doesn't match");
        } else {
            this.taResult.setText(searched.toString());
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdId;
    private javax.swing.JRadioButton rdName;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField txtEntry;
    // End of variables declaration//GEN-END:variables
}
